import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { DefaultFooter } from "./components/ui/Footer";
import { DefaultHeader } from "./components/ui/Header";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col bg-gray-100">
          <DefaultHeader />

          <main className="flex-1 container mx-auto p-4">
            {children}
          </main>

          <DefaultFooter label="© 2025 Netdy" />
        </div>
      </body>
    </html>
  );
}
